name: Publish snapshot

on:
  workflow_dispatch:

jobs:
  publish:
    name: Build and publish
    runs-on: ubuntu-latest

    environment: Default

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and publish with gradlew
        env:
          OSSRH_USERNAME: "NOT ACTUALLY MY USERNAME"
          OSSRH_PASSWORD: "NOT REALLY MY PASSWORD"
        run: ./gradlew publishAllPublicationsToSnapshotRepository -x lint
